project_id = "slamtlgebisrimijeoid"

[functions.create-checkout-session]
verify_jwt = true

[functions.create-cart-checkout]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = true

[functions.ai-generate-city-content]
verify_jwt = true

[functions.generate-bulk-topic-posts]
verify_jwt = true

[functions.generate-platform-marketing-post]
verify_jwt = false

[functions.get-scheduled-posts]
verify_jwt = false

[functions.auto-generate-blog-article]
verify_jwt = false

[functions.send-blog-webhook]
verify_jwt = true
