project_id = "slamtlgebisrimijeoid"

[functions.create-checkout-session]
verify_jwt = true

[functions.create-cart-checkout]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false